### ISSUE TITLE
Locator vs `acceldecel` mode

### ISSUE THREAD

**Issue by emilymdubois** [mapbox/guidance-replay#8]
As of now, I'm [using time](https://github.com/mapbox/guidance-replay/blob/803765a01c19af20e73235574bf74ee4f9c541b5/lib/locator.js#L46-L54) to keep track of what step we're on in the route. Current step is a [required parameter](https://github.com/mapbox/navigation.js/blob/47a767fba48a736e9c705c58ec0b40380046f387/index.js#L58) for integration with `navigation.js`.

This works great when `"spacing": "constant"`, but the instructions start to behave unexpectedly around maneuvers. I think this is because we formulaically ease from the speed of the current segment into the speed of the next segment, which offsets our current time & coordinate combination from the expectation. At maneuvers, we are farther along the route than is expected by the function.

I'm trying to think of a solution that better integrates with `"spacing": "acceldecel"` mode. I could reattempt distance-based step identification, but had ultimately decided on time-based identification after struggling with [highway cloverleaf interchanges](http://media.web.britannica.com/eb-media/94/93494-004-8BE9B9F2.jpg). I wonder if there's a way to pull in `speedChange` into the [Locator](https://github.com/mapbox/guidance-replay/blob/803765a01c19af20e73235574bf74ee4f9c541b5/lib/locator.js) to better prepare for maneuvers.

cc @yhahn @emilymcafee

**Comment by emilymdubois** [comment]
Explained in some more detail here as well: [`directions-sim` issue #3](https://github.com/mapbox/directions-sim/issues/3#issuecomment-220663578)

**Comment by emilymcafee** [comment]
Per chat, we're thinking [this function](https://github.com/mapbox/guidance-replay/blob/803765a01c19af20e73235574bf74ee4f9c541b5/lib/route.js#L161-L171) maaay be able to help. 🔍

**Comment by emilymdubois** [comment]
Closed via [PR #9](https://github.com/mapbox/guidance-replay/pull/9)
